## Deploys a Kerberized server box
---
- name: Apply configuration to a domain controller client
  hosts: all
  remote_user: local-admin
  become: true

  vars:
    sssd_admin_only: true
    shm_mount_options: ['defaults', 'nodev', 'nosuid', 'noexec']

  vars_prompt:
    - name: "kadmin_pwd"
      prompt: "Provide kadmin password to fetch kerberos keytab.\nLeave empty if done already"
      private: true

  roles:
    - upgrade_system
    - unattended_upgrades
    - hardening
    - firewall
    - timesyncd
    - kerberize
