---
## Deploys a LDAP/Kerberos server with SASL passthrough
## Add 'hostname=XXX' and 'domain=YYY' to installer boot parameters to set hostname/domain

- name: Apply configuration to the domain controller
  hosts: all
  remote_user: ansible
  become: true

  vars:
    di_dist: "{{ ansible_distribution_release }}"
    di_version: "{{ ansible_distribution_major_version }}"
    di_pkg: "debian-installer-{{ di_version }}-netboot-amd64"

    ansible_user: ansible
    repo_dir: "/home/{{ ansible_user }}/debian-lan"

  roles:
    - upgrade_system
    - unattended_upgrades
    - krb5_ldap_sasl
    - kerberize
