## Deploys a LDAP/Kerberos server
---

- name: Apply configuration to the domain controller
  hosts: all
  remote_user: ansible
  become: true

  vars:
    sssd_admin_only: true

  roles:
    - upgrade_system
    - unattended_upgrades
    - firewall
    - krb5_ldap_sasl
#    - kerberize
